name: Go Code Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v6.1.0

    - name: Gosec Security Checker
      uses: securego/gosec@v2.21.3
